[build]
buildCommand = "composer install --optimize-autoloader --no-scripts --no-interaction && npm ci && npm run build"
startCommand = "/start-container.sh"

[deploy]
startCommand = "php artisan migrate --force"

